src/business-logic/services/rundown-event-builder-implementation.ts
src/business-logic/services/rundown-timeline-service.ts
src/business-logic/services/superfly-timeline-builder.ts
src/model/entities/rundown.ts
src/model/entities/test/entity-mock-factory.ts
src/model/entities/test/rundown.spec.ts
src/model/value-objects/rundown-event.ts

This PR is dependent on: https://github.com/tv2/sofie-server/pull/10
It also has breaking changes for the RundownActivatedEvent that has been fixed in: https://github.com/tv2/ng-sofie/pull/24
The Rundown no longer perfoms a Take on activation.
To achieve this, it has been necessary to make the active Part and active Segment on the Rundown optional.

SOF-1523 No longer does a Take on activation of Rundown

---

src/business-logic/services/interfaces/rundown-event-emitter.ts
src/business-logic/services/rundown-timeline-service.ts
src/model/entities/part.ts
src/model/entities/rundown.ts
src/model/entities/test/rundown.spec.ts
src/presentation/dtos/piece-dto.ts
src/presentation/interfaces/rundown-event-builder.ts
src/presentation/services/rundown-event-builder-implementation.ts
src/presentation/services/rundown-event-service.ts
src/presentation/value-objects/rundown-event.ts

- Added segment id, and part id to piece inserted event, to have the rundown cursor data present as in the other part related events.
- Resets part right before changing next cursor to remove unplanned pieces.

Expose Rundown Cursor information on piece inserted event

---

src/blueprints/tv2/action-factories/tv2-remote-action-factory.ts

`Tv2SourceMappingWithSound._id` is the id created by MongoDB. `.SourceName` is currently the number 1 through 5. 
This is to use the number so the Action is more recognizable

SOF-1628 User source.SourceName instead of _id for Remote Actions

---

src/blueprints/tv2/action-factories/tv2-dve-action-factory.ts
src/blueprints/tv2/action-factories/tv2-graphics-action-factory.ts
src/blueprints/tv2/action-factories/tv2-video-clip-action-factory.ts
src/blueprints/tv2/tv2-action-service.ts
src/blueprints/tv2/value-objects/tv2-action-manifest-data.ts
src/business-logic/services/execute-action-service.ts
src/business-logic/services/interfaces/action-service.ts
src/data-access/repositories/interfaces/action-manifest-repository.ts
src/data-access/repositories/mongo/mongo-action-manifest-repository.ts
src/data-access/repositories/mongo/mongo-ad-lib-actions-repository.ts
src/data-access/repositories/mongo/mongo-ad-lib-piece-repository.ts
src/model/entities/action.ts
src/presentation/controllers/action-controller.ts

NOTE: The target branch for this PR is the branch for #28. Reviewing that one before this is adviced. 
- Adds filtering of AdLibPieces/AdLibActions extracted from database, to only be the ones for the requested rundownId.
- Adds rundownId to actions generated from ActionManifests.
Has been tested locally, ensureing that only actions for the specified rundownId is returned.
Let me know if there are other actions being generated, that are rundown specific, other than those generated from ActionManifests.

(SOF-1692) Only generate/return general and specified rundown actions

---

src/business-logic/services/execute-action-service.ts
src/data-access/repositories/interfaces/action-repository.ts
src/data-access/repositories/mongo/mongo-action-repository.ts
src/presentation/controllers/action-controller.ts

NOTE: The base of this is the branch for #48. Reviewing that one before this is adviced.
- Adds deletion of rundown specific actions, prior to saving newly generated ones.
Has been verified locally, that actions with the specified rundown id is the only actions being removed by the new call.

(SOF-1691) Delete rundown actions before saving new ones.

---

src/blueprints/timeline-state-resolver-types/caspar-cg-types.ts
src/blueprints/tv2/timeline-object-factories/tv2-caspar-cg-timeline-object-factory.ts

- CasparCG template slot names are using the enumeration `CasparCgTemplateSlotType`.
- The `display` attribute uses the enum `CasparCgTemplateDisplayMode`.
- Split screen style is an object instead of string (and defaults to an empty object).
- `mapTv2GraphicsLayerToHtmlGraphicsSlot` is removed, since it was only used in places where we already knew the outcome.

SOF-1695: CasparCG slot referencing

---

src/blueprints/tv2/action-factories/tv2-graphics-action-factory.ts
src/blueprints/tv2/timeline-object-factories/tv2-viz-timeline-object-factory.ts

Our Fullscreen Actions for Viz was missing a `classes=['full']`.
The `classes` attribute is used by the Timeline Resolver to determine enables and can be used like `enable: { while: '!.full' }` which means while there is no objects with the class "full", then put this on the Timeline.
All our Idents is ingested by Blueprints with the above enable. For some reason, if the VCP does not have the `classes=['full']` a command is send to Viz to clear the VCP when it's been taken from an Ident. (I am not entirely sure why, but the working theory is that the Ident clear command takes precedent, but having the class "full" somehow 'cancels' that precedent.)
Ideally, we would like to avoid using the `classes` attribute since it's an extra complication in the Timeline Resolving (it does have its …

SOF-1703 Add classes='full' to VCP Piece so Ident won't take precedent

---

.github/workflows/publish-image.yml

Adds GitHub Action workflow for publishing a new Docker image to Docker Hub with `workflow_dispatch` as the trigger.
For the workflow dispatch information, the branch to publish from should be selected along with the version tag to use.
The version tag should be written as a semantic version (e.g.`46.3.1` or `46.3.1-staging`).
The necessary secrets are added to the repository.

SOF-1723: Simple 'Publish Image' workflow.

---

src/business-logic/services/database-change-ingest-service.ts
src/business-logic/services/ingested-entity-to-entity-mapper.ts

Note: This is dependent on PR https://github.com/tv2/sofie-server/pull/69
Updating a Segment from IngestedSegment now also update the Parts of the Segment, if the Part belongs in the IngestedSegment.

SOF-1760 Parts are also updated on "Reload iNews data"

---

src/presentation/controllers/action-controller.ts
src/presentation/controllers/test/action-controller.spec.ts

When executeAction receives null for the value of actionArguments, it converts it to undefined

SOF-1768 Sanitize null for ActionTrigger ActionArguments

---

src/business-logic/services/execute-action-service.ts
src/business-logic/services/interfaces/action-service.ts
src/data-access/repositories/mongo/mongo-action-repository.ts
src/presentation/controllers/action-controller.ts

Now exposes an endpoint that can fetch all Actions without giving a RundownId. The endpoint won't return any Actions that are specific to a Rundown.

SOF-1769 Expose endpoint to fetch Actions without a RundownId

---

src/data-access/repositories/cache/cached-configuration-repository.ts
src/data-access/repositories/interfaces/configuration-repository.ts
src/data-access/repositories/mongo/mongo-configuration-repository.ts
src/data-access/repositories/test/configuration-controller.spec.ts
src/data-access/repositories/test/mongo-configuration-repository.spec.ts
src/presentation/controllers/configuration-controller.ts

note: implementation re-take-2 - replaces https://github.com/tv2/sofie-server/pull/76 due to commit history being rewritten badly in attempt to sign all my unsigned commits.
task: We should be able to reset configuration cache without restarting the application.
For this - here I'm adding endpoint that will set cached configuration to undefined.
Also a button in config page that performs POST request to the reset endpoint https://github.com/tv2/ng-sofie/pull/85

SOF-1754 - Reset configuration cache with an endpoint request

---

src/business-logic/services/ingested-entity-to-entity-mapper.ts
src/data-access/repositories/mongo/mongo-ad-lib-actions-repository.ts
src/data-access/repositories/mongo/mongo-entity-converter.ts
src/data-access/repositories/mongo/mongo-ingested-entity-converter.ts
src/model/entities/ingested-segment.ts
src/model/entities/rundown.ts
src/model/entities/segment.ts
src/model/entities/test/entity-mock-factory.ts
src/model/entities/test/rundown.spec.ts
src/model/exceptions/last-segment-in-rundown-exception.ts
src/model/exceptions/last-segment-in-rundown.ts
src/presentation/dtos/segment-dto.ts

- Segments now exposes `isHidden`
- Segments now exposes a `metadata` field
- Sofie Server now loads all "hidden" Segments and Segments with no Parts and sends them to the frontend so the frontend can decide what to do with them.
- Sofie Server now supports empty and hidden Segments when executing a Rundown (they are ignored in the execution and they are not possible to be Taken)

Sof 1719/update segments with mini shelf

---

src/data-access/repositories/mongo/mongo-entity-converter.ts

The duration for Media is saved as a string in the database.
Media.duration is now an actual number and the value is in milliseconds when fetching it.

SOF-1791 Return correct type and format for Media.duration

---

src/model/entities/rundown.ts
src/model/entities/test/rundown.spec.ts

When we reached the last Part of the last Segment, both the OnAirCursor and the NextCursor was pointing on the same Part.
This meant, that when we did `this.nextCursor.part.reset()` we also reset the OnAir Part removing the `timings` of the OnAir Part.
This caused an exception to happen when we tried to build the TimelineGroup for the Active Part.
We no longer reset the NextCursor.Part when doing a setNext if the OnAirCursor points to the same Part.
Also, did a slight refactoring to no longer have a try-catch nested within a try-catch.

SOF-1783 No longer reset the NextCursor.part if the Part is also OnAir

---

src/blueprints/tv2/action-factories/tv2-video-clip-action-factory.ts

If we had multiple VideoClip Actions for the same video file, all the VideoClipAsNextAction would get the same id, which is bad.
This makes the id's more unique by also including the Segment name in the id.
It's not ideal, but it's the best we got until we can generate the Actions during the Ingest flow.

SOF-1721 Make ids of VideoClipAsNextActions more unique

---

src/business-logic/services/rundown-timeline-service.ts
src/business-logic/services/test/rundown-timeline-service.spec.ts
src/model/entities/test/entity-test-factory.ts

Inserting a Part as on Air will now keep any already inserted Part as Next if there is one.
Also did some minor cleanup in the EntityTestFactory.

SOF-1675 No longer Removing Next when inserting as OnAir.

---

src/business-logic/services/execute-action-service.ts
src/business-logic/services/test/execute-action-service.spec.ts
src/model/entities/part.ts
src/presentation/dtos/part-dto.ts

Parts created from an Action now includes the ActionId on its metadata.
I decided to make an actually interface for `PartMetadata` instead of `unknown` since this is logic that SofieServer handles.

SOF-1796 Add ActionId to Parts

---

src/blueprints/tv2/action-factories/tv2-video-clip-action-factory.ts

Piece on VideoClipAction should use the filename of the VideoClip as Piece.name

SOF-1812 Use filename as name for VideoClipAction pieces

---

src/blueprints/tv2/helpers/tv2-show-style-blueprint-configuration-mapper.ts
src/blueprints/tv2/tv2-blueprint-configuration-validator.ts
src/blueprints/tv2/tv2-blueprint.ts
src/blueprints/tv2/tv2-blueprints-facade.ts
src/blueprints/tv2/value-objects/tv2-show-style-blueprint-configuration.ts
src/business-logic/facades/service-facade.ts
src/business-logic/services/configuration-changed-service.ts
src/business-logic/services/device-changed-service.ts
src/business-logic/services/ingest-data-changed-service.ts
src/business-logic/services/interfaces/data-change-service.ts
src/business-logic/services/interfaces/database-change-service.ts
src/business-logic/services/interfaces/status-message-service.ts
src/business-logic/services/media-database-changed-service.ts
src/business-logic/services/status-message-service-implementation.ts
src/business-logic/services/test/device-changed-service.spec.ts
src/business-logic/services/test/status-message-service-implementation.spec.ts
src/data-access/facades/repository-facade.ts
src/data-access/repositories/interfaces/database.ts
src/data-access/repositories/interfaces/status-message-repository.ts
src/data-access/repositories/mongo/mongo-database.ts
src/data-access/repositories/mongo/mongo-show-style-configuration-changed-listener.ts
src/data-access/repositories/mongo/mongo-status-message-repository.ts
src/model/value-objects/blueprint.ts
src/presentation/index.ts

Introduce `BlueprintValidateConfiguration` which is a callback function that SofieServer can call in Blueprints in order to validate the company spcific Blueprint configurations.
The callback returns a list of `StatusMessages` that each refers to an error in the configuration.
SofieServer will notify all clients of these errors and when the error is no longer there, it will automatically notify the clients about this as well. In this implementation we are only validating `GraphicsSchemas`, but it's easy to extend as needed.
For now SofieServer is listening for whenever the ShowStyle collection changes in the database and then validates the configuration. Once we are no longer reliant on Core, we can call the ValidateConfiguration just before we save updates from the …

SOF-1789 Introduce Validate blueprints configuration hook
